### ISSUE TITLE
Block commands fail if the response isn't json

### ISSUE THREAD

**Issue by hansmosh** [neutralio/pynio#29]
Steps to reproduce:
1) Command block 'logger' to 'log' in service 's'
`s.command('log', logger)`

Problem:
r.json fails in  REST._get

Potential Solution:
If json decode fails, return r.text instead

What is the point of the decode_json flag? Maybe instead of decode_json=True, the flag could be raw_response=False and when raw_response is true, the Response object r is returned.

Ex:
if raw_response:
    return r
else:
    try:
        return r.json()
    escept:
        return r.text

**Comment by cloudformdesign** [comment]
I like it, please make the change.

**Comment by cloudformdesign** [comment]
changes are done, see PR above
